name: 'QA_Action_docker_image_161'
description: 'Docker action using a public image reference'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we greeted you'
runs:
  using: docker
  image: 'docker://alpine:3.19'
  args:
    - "${{ inputs.who-to-greet }}"
